### ISSUE TITLE
gelf preprocessor can panic on bad data

### ISSUE THREAD

**Issue by Licenser** [wayfair-tremor/tremor-runtime#115]
**Problem**

when receiving invalid data the Gelf preprocessor can panic.

**Steps**

Send a gelf datagram with less then two bytes.

**Possible Solution(s)**

https://github.com/wayfair-tremor/tremor-runtime/blob/master/src/preprocessor/gelf.rs#L119 assumes at least two bytes being present, that, however, isn't guaranteed always the case. We need to handle this more carefully.

**Notes**
```
kubectl logs wf-tremor-2g224  -n wf-tremor
+ '[' '!' -z ']'
+ '[' -z ']'
+ LOGGER_FILE=/etc/tremor/logger.yaml
++ ls -1 '/etc/tremor/config/*.trickle'
++ wc -l
+ queries=0
+ '[' 0 '!=' 0 ']'
+ exec ./tremor-server --config /etc/tremor/config/config.yaml --logger-config /etc/tremor/logger.yaml
tremor version: 0.6.0
rd_kafka version: 0x000001ff, 1.2.1
Listening at: http://0.0.0.0:9898
thread 'onramp-udp-???' panicked at 'index out of bounds: the len is 1 but the index is 1', src/preprocessor/gelf.rs:119:72
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

```yaml
    onramp:
      - id: udp
        type: udp
        preprocessors:
          - decompress
          - gelf-chunking
          - decompress
        codec: json
        config:
          port: 12201
          host: '0.0.0.0'
    offramp:
      - id: kafka-out
        type: kafka
        config:
          brokers:
            - REDACTED:9092
            - REDACTED:9092
            - REDACTED:9092
            - REDACTED:9092
            - REDACTED:9092
          topic: REDACTED
    pipeline:
      - id: main
        interface:
          inputs:
            - in
          outputs:
            - out
        nodes:
          - id: passthrough
            op: passthrough
        links:
          in: [ passthrough ]
          passthrough: [ out ]
    # define interconnect
    binding:
      - id: default
        links:
          '/onramp/udp/{instance}/out': [ '/pipeline/main/{instance}/in' ]
          '/pipeline/main/{instance}/out': [ '/offramp/kafka-out/{instance}/out' ]
    mapping:
      /binding/default/01:
        instance: '01'
```
