### ISSUE TITLE
'Runtime' node port 'in' metrics are missing in tremor-0.7.4-alpha verison

### ISSUE THREAD

**Issue by rajasimha1991** [wayfair-tremor/tremor-runtime#211]
**Problem**
We recently upgraded tremor from `0.6.1` to `0.7.4alpha` version. After upgrading we are not able to collect metrics for `runtime` node `in` port. We were able to collect metrics in the earlier version.

**Steps**
1. Add the metrics pipeline
```
binding:
  - id: metrics
    links:
      '/pipeline/system::metrics/system/out':  ["/offramp/system::stdout/system/in"]
```

**Notes**

Output of `rustup --version`:
Output of `rustup show`:
Output of `tremor-server --version`: tremor:0.7.4-alpha
