### ISSUE TITLE
Tremor not logging any error when a Kafka offramp fails to start

### ISSUE THREAD

**Issue by anuprout** [wayfair-tremor/tremor-runtime#77]
**Problem**
Hi, It was observed that Tremor is not logging any error when a Kafka offramp is failed to start. In my case, there was a syntactical error in Kafka offramp config where I was not using string format for one of the **rdkafka_options**. As a result the underlying Kafka producers could not be started . However Tremor didn't throw any error while the service was started. 

**Steps**

1. Create an off ramp with below config.
```
offramp:
- id: kafka
  type: kafka
  metrics_interval_s: 10
  codec: influx
  config:
    brokers:
    - <some broker host:port>
   topic: <some topic>
    rdkafka_options:
      enable.idempotence: true
      **max.in.flight.requests.per.connection: 5**  ## pass in Integer format
```

2. start Tremor service & verify the service status 
3. Check Tremor log

**Possible Solution(s)**

1. Please see if the error handing can be implemented in such cases.
2. It would also be great if Tremor can refactor the formats before passing to "rdkafka". 

**Notes**
```
tremor-runtime:0.6.0
rd_kafka version: 1.2.1
```

(edit by @Licenser to add code blocks for readability)
